// --- script.js (FINAL & CORRECTED) ---
document.addEventListener('DOMContentLoaded', () => {
    initializePage();
    if (document.getElementById('appointmentForm') || document.getElementById('careerForm') || document.getElementById('contactForm')) {
        initializeForm();
    }
});

function initializePage() {
    document.body.classList.remove('fade-out');
    changeLanguage('en');
    const yearSpan = document.getElementById('year');
    if(yearSpan) yearSpan.textContent = new Date().getFullYear();
    window.addEventListener('scroll', revealOnScroll);
    revealOnScroll();

    const menuToggle = document.getElementById('menu-toggle');
    const closeMenu = document.getElementById('close-menu');
    const overlayMenu = document.getElementById('overlay-menu');
    if (menuToggle && overlayMenu && closeMenu) {
        menuToggle.addEventListener('click', () => overlayMenu.classList.add('open'));
        closeMenu.addEventListener('click', () => overlayMenu.classList.remove('open'));
    }
    
    const header = document.querySelector('.main-header');
    if(header){
        window.addEventListener('scroll', () => {
            if (window.scrollY > 50) {
                header.classList.add('scrolled');
            } else {
                header.classList.remove('scrolled');
            }
        });
    }

    const navLinks = document.querySelectorAll('a:not([target="_blank"]):not([href^="#"]):not([href^="mailto:"])');
    navLinks.forEach(link => {
        link.addEventListener('click', e => {
            const href = link.getAttribute('href');
            if (href && href !== '#' && !href.startsWith('javascript:')) {
                e.preventDefault();
                document.body.classList.add('fade-out');
                setTimeout(() => {
                    window.location.href = href;
                }, 400);
            }
        });
    });
}

function revealOnScroll() {
    const reveals = document.querySelectorAll('.reveal');
    reveals.forEach(reveal => {
        const windowHeight = window.innerHeight;
        const elementTop = reveal.getBoundingClientRect().top;
        const elementVisible = 100;
        if (elementTop < windowHeight - elementVisible) {
            reveal.classList.add('active');
        }
    });
}

function changeLanguage(lang) {
    document.documentElement.lang = lang;
    document.querySelectorAll('.lang-switcher button').forEach(btn => btn.classList.remove('active'));
    const activeBtn = document.getElementById(`lang-${lang}`);
    if(activeBtn) activeBtn.classList.add('active');

    const elements = document.querySelectorAll('[data-lang]');
    elements.forEach(el => {
        const key = translations[lang]?.[el.getAttribute('data-lang')];
        if (key) {
            if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                el.placeholder = key;
            } else {
                el.innerHTML = key;
            }
        }
    });

    if (document.getElementById('countrySelect')) {
        populateCountryDropdown();
    }
}

function initializeForm() {
    const countrySelect = document.getElementById('countrySelect');
    if(countrySelect){
        populateCountryDropdown();
        countrySelect.addEventListener('change', updateCityDropdown);
    }
}

function populateCountryDropdown() {
    const countrySelect = document.getElementById('countrySelect');
    if (!countrySelect) return;
    const currentLang = document.documentElement.lang;
    const currentCountryValue = countrySelect.value; 
    countrySelect.innerHTML = '';
    
    Object.keys(cityData).forEach(countryCode => {
        const option = document.createElement('option');
        option.value = countryCode;
        option.textContent = cityData[countryCode].name[currentLang];
        countrySelect.appendChild(option);
    });

    if (currentCountryValue) {
        countrySelect.value = currentCountryValue;
    }
    updateCityDropdown();
}

function updateCityDropdown() {
    const countrySelect = document.getElementById('countrySelect');
    const citySelect = document.getElementById('citySelect');
    if (!countrySelect || !citySelect) return;
    const selectedCountry = countrySelect.value;
    const currentLang = document.documentElement.lang;
    
    citySelect.innerHTML = '';
    if (cityData[selectedCountry] && cityData[selectedCountry].cities) {
        cityData[selectedCountry].cities.forEach(city => {
            const option = document.createElement('option');
            option.value = city.code;
            option.textContent = city.name[currentLang];
            citySelect.appendChild(option);
        });
    }
}

const cityData = {
    de: { name: { en: 'Germany', tr: 'Almanya', el: 'Γερμανία', fr: 'Allemagne' }, cities: [ { code: 'ber', name: { en: 'Berlin', tr: 'Berlin', el: 'Βερολίνο', fr: 'Berlin' } }, { code: 'mun', name: { en: 'Munich', tr: 'Münih', el: 'Μόναχο', fr: 'Munich' } }, { code: 'fra', name: { en: 'Frankfurt', tr: 'Frankfurt', el: 'Φρανκφούρτη', fr: 'Francfort' } }, { code: 'ham', name: { en: 'Hamburg', tr: 'Hamburg', el: 'Αμβούργο', fr: 'Hambourg' } } ] },
    gr: { name: { en: 'Greece', tr: 'Yunanistan', el: 'Ελλάδα', fr: 'Grèce' }, cities: [ { code: 'ath', name: { en: 'Athens', tr: 'Atina', el: 'Αθήνα', fr: 'Athènes' } }, { code: 'the', name: { en: 'Thessaloniki', tr: 'Selanik', el: 'Θεσσαλονίκη', fr: 'Thessalonique' } }, { code: 'pat', name: { en: 'Patras', tr: 'Patra', el: 'Πάτρα', fr: 'Patras' } } ] },
    tr: { name: { en: 'Turkey', tr: 'Türkiye', el: 'Τουρκία', fr: 'Turquie' }, cities: [ { code: 'ist', name: { en: 'Istanbul', tr: 'İstanbul', el: 'Κωνσταντινούπολη', fr: 'Istanbul' } }, { code: 'ank', name: { en: 'Ankara', tr: 'Ankara', el: 'Άγκυρα', fr: 'Ankara' } }, { code: 'izm', name: { en: 'Izmir', tr: 'İzmir', el: 'Σμύρνη', fr: 'Izmir' } }, { code: 'ant', name: { en: 'Antalya', tr: 'Antalya', el: 'Αττάλεια', fr: 'Antalya' } } ] },
    fr: { name: { en: 'France', tr: 'Fransa', el: 'Γαλλία', fr: 'France' }, cities: [ { code: 'par', name: { en: 'Paris', tr: 'Paris', el: 'Παρίσι', fr: 'Paris' } }, { code: 'mar', name: { en: 'Marseille', tr: 'Marsilya', el: 'Μασσαλία', fr: 'Marseille' } }, { code: 'lyo', name: { en: 'Lyon', tr: 'Lyon', el: 'Λυών', fr: 'Lyon' } } ] },
    it: { name: { en: 'Italy', tr: 'İtalya', el: 'Ιταλία', fr: 'Italie' }, cities: [ { code: 'rom', name: { en: 'Rome', tr: 'Roma', el: 'Ρώμη', fr: 'Rome' } }, { code: 'mil', name: { en: 'Milan', tr: 'Milano', el: 'Μιλάνο', fr: 'Milan' } }, { code: 'nap', name: { en: 'Naples', tr: 'Napoli', el: 'Νάπολη', fr: 'Naples' } } ] },
    es: { name: { en: 'Spain', tr: 'İspanya', el: 'Ισπανία', fr: 'Espagne' }, cities: [ { code: 'mad', name: { en: 'Madrid', tr: 'Madrid', el: 'Μαδρίτη', fr: 'Madrid' } }, { code: 'bar', name: { en: 'Barcelona', tr: 'Barselona', el: 'Βαρκελώνη', fr: 'Barcelone' } } ] },
    gb: { name: { en: 'United Kingdom', tr: 'Birleşik Krallık', el: 'Ηνωμένο Βασίλειο', fr: 'Royaume-Uni' }, cities: [ { code: 'lon', name: { en: 'London', tr: 'Londra', el: 'Λονδίνο', fr: 'Londres' } }, { code: 'man', name: { en: 'Manchester', tr: 'Manchester', el: 'Μάντσεστερ', fr: 'Manchester' } } ] },
    us: { name: { en: 'United States', tr: 'ABD', el: 'ΗΠΑ', fr: 'États-Unis' }, cities: [ { code: 'nyc', name: { en: 'New York', tr: 'New York', el: 'Νέα Υόρκη', fr: 'New York' } }, { code: 'la', name: { en: 'Los Angeles', tr: 'Los Angeles', el: 'Λος Άντζελες', fr: 'Los Angeles' } }, { code: 'chi', name: { en: 'Chicago', tr: 'Chicago', el: 'Σικάγο', fr: 'Chicago' } } ] },
    se: { name: { en: 'Sweden', tr: 'İsveç', el: 'Σουηδία', fr: 'Suède' }, cities: [ { code: 'sto', name: { en: 'Stockholm', tr: 'Stockholm', el: 'Στοκχόλμη', fr: 'Stockholm' } } ] },
    ch: { name: { en: 'Switzerland', tr: 'İsviçre', el: 'Ελβετία', fr: 'Suisse' }, cities: [ { code: 'zur', name: { en: 'Zurich', tr: 'Zürih', el: 'Ζυρίχη', fr: 'Zurich' } }, { code: 'gen', name: { en: 'Geneva', tr: 'Cenevre', el: 'Γενεύη', fr: 'Genève' } } ] },
    cy: { name: { en: 'Cyprus', tr: 'Kıbrıs', el: 'Κύπρος', fr: 'Chypre' }, cities: [ { code: 'nic', name: { en: 'Nicosia', tr: 'Lefkoşa', el: 'Λευκωσία', fr: 'Nicosie' } } ] },
    dk: { name: { en: 'Denmark', tr: 'Danimarka', el: 'Δανία', fr: 'Danemark' }, cities: [ { code: 'cop', name: { en: 'Copenhagen', tr: 'Kopenhag', el: 'Κοπεγχάγη', fr: 'Copenhague' } } ] }
};
const translations = {
    en: {
        slogan: "Power of Europe", aboutTitle: "About Us", aboutParagraph: "Headquartered in Athens, Greece, KyroServices Global is a dynamic parent company operating throughout Europe and Turkey. We manage a diverse portfolio of specialized brands, delivering excellence and innovation across a wide range of industries.", address: "Leoforos Kifisias 123, Marousi, 151 24 Athens, Greece", brandsTitle: "Our Brands & Operations", opsTurkeyTitle: "Franchise Operations", opsTurkeyParagraph: "2 Burger King branches (Vadi Istanbul, Bodrum) and all Starbucks stores in the Bodrum region are operated by us.", teamTitle: "Our Board of Directors", team_kyros_name: "Kyros I. DUGAN", team_kyros_title: "Founder & Owner", team_alissa_name: "Alissa KIRAKIS", team_alissa_title: "General Director, KyroServices Global", team_gamze_name: "Gamze ÖZDEN", team_gamze_title: "General Director, KyroServices Turkey & Yunandan Gelsin", team_dimitri_name: "Dimitri LYANOS", team_dimitri_title: "General Director, K&D History Services Europe & USA", team_beyza_name: "Beyza ÇİMEN", team_beyza_title: "General Director, K&D History Services Turkey", team_sadio_name: "Mehmet Sadioğlu", team_sadio_title: "General Manager, PeP", team_fatma_name: "Fatma BAYSAN", team_fatma_title: "General Manager, Kosmos Vize", team_fevzi_name: "Fevzi Cem İz", team_fevzi_title: "General Manager, Kampüs Giyim", team_tugce_name: "Müh. Tuğçe SARICA", team_tugce_title: "General Manager, ReziKyros", team_hande_name: "Hande DERİN", team_hande_title: "General Coordinator, Burger King & Starbucks Franchises", strategyTitle: "Our Strategic Vision", strategyParagraph: "Our vision is to foster synergy between our diverse brands, driving innovation and sustainable growth. We are committed to excellence and expanding our global footprint while delivering exceptional value to our clients and partners worldwide.", contactTitle: "Get In Touch", contactSubtitle: "Feel free to reach out for projects and collaborations.", contactButton: "Contact Us",
        menu_home: "Home", menu_about: "About Us", menu_team: "Board", menu_brands: "Our Brands", menu_career: "Career", menu_contact: "Contact", menu_kd: "K&D History Services", menu_pep: "PeP", menu_yunan: "Yunandan Gelsin", menu_kampus: "Kampüs Giyim", menu_rezi: "ReziKyros", menu_kosmos: "Kosmos Vize",
        brand_desc_kd: "As an official NATO partner, it provides historical consultancy and geopolitical analysis services in 12 countries.", brand_desc_pep: "An electronic money institution supervised by the CBRT, offering international money transfer and digital wallet solutions.", brand_desc_yunan: "Presents authentic and traditional products of Greece to consumers through its stores in Turkey and its e-commerce platform.", brand_desc_kampus: "Produces customizable, design-oriented apparel and promotional products for schools, sports teams, and companies.", brand_desc_rezi: "Develops high-standard luxury residential and commercial construction projects in Turkey and Europe with a focus on trust and quality.", brand_desc_kosmos: "As the sole official authorized visa application center for the Consulate of Greece in Turkey, it offers Schengen and national visa services.",
        about_page_title: "About KyroServices Global", about_section1_title: "Our Story & Vision", about_section1_p1: "KyroServices Global was founded in Athens in 2012 with the vision of our founder, Kyros I. Dugan, not only to be a group of companies operating in different sectors, but also to build an economic and cultural bridge between Europe and Turkey. Combining inspiration from the depths of history with the technologies of the future, our company has aimed to redefine standards in every sector it has entered since its inception.", about_section1_p2: "Our journey, which initially started in niche areas such as historical consultancy and visa services, has quickly expanded to a wide range of fields including textiles, food, construction, and financial technologies, becoming an international force.", about_section2_title: "Our Mission & Values", about_section2_p1: "Our mission is to create a sustainable and innovative growth model by creating synergy among all our group companies, while ensuring that each of our brands is a leader in its own field. We place customer satisfaction and quality above all else.", value1: "<strong>Quality:</strong> We aim for the highest standards in every product and service we offer.", value2: "<strong>Trust:</strong> We build our relationships with all our stakeholders on transparency and honesty.", value3: "<strong>Innovation:</strong> We challenge the status quo and develop innovative solutions that shape our industries.", value4: "<strong>Global Perspective:</strong> We think and act on a global scale while respecting local values.",
        team_page_title: "Our Board of Directors", team_kyros_bio: "The visionary founder of KyroServices Global, steering the group with a unique perspective that blends historical depth with future-oriented strategies.", team_alissa_bio: "Manages the overall global operations and strategic direction of the group, ensuring synergy and growth across all brands.", team_gamze_bio: "Leads operations in the dynamic Turkish market and also directs the 'Yunandan Gelsin' brand, bridging two cultures.", team_dimitri_bio: "Heads the historical consultancy services across Europe and the USA, providing critical insights to governments and organizations.", team_beyza_bio: "Directs the Turkish operations of K&D History Services, adapting global expertise to the local historical context.", team_sadio_bio: "Leads the innovative financial technology brand PeP, driving its expansion in the digital payment landscape.", team_fatma_bio: "Manages Kosmos Vize, the sole official visa application center for Greece in Turkey, ensuring seamless service.", team_fevzi_bio: "Directs the Kampüs Giyim brand, focusing on providing customized apparel for educational and corporate clients.", team_tugce_bio: "Leads the ReziKyros construction brand, focusing on developing high-quality, reliable real estate projects.", team_hande_bio: "Coordinates the successful operation of the Burger King and Starbucks franchises, maintaining high standards of quality and service.",
        career_page_title: "Career at KyroServices Global", career_section1_title: "Join Our Family", career_section1_p1: "At KyroServices Global, we believe our greatest asset is our people. We foster a supportive, collaborative, and dynamic work environment where every team member is valued and has the opportunity to grow. We are a family that builds success together, celebrating both individual and collective achievements.", career_section2_title: "What We Offer", career_section2_p1: "We provide our employees with a competitive compensation package, comprehensive benefits, and continuous opportunities for professional development. We invest in our team's growth because we know that the success of our company is built on the expertise and passion of our employees.", career_section3_title: "General Application", career_section3_p1: "We are always looking for talented and passionate individuals to join our team. If you believe you have what it takes to contribute to our success, please send your resume to our Human Resources department.",
        contact_page_title: "Contact Us", contact_greece_title: "Global Headquarters (Athens)", contact_turkey_title: "Turkey Headquarters (Istanbul)", contact_form_title: "Send Us a Message",
        kd_presence_title: "Global Presence", kd_presence_text: "Operating with <strong>73 offices in 12 countries</strong>, our reach is a testament to our expertise and trusted partnerships.", kd_partner_title: "NATO Partner", kd_partner_text: "We are proud to be an <strong>Official Partner of NATO</strong>, providing critical historical and geopolitical consultancy.",
        kd_expertise_title: "Our Expertise", kd_service1_title: "Historical Consultancy", kd_service1_desc: "Providing strategic insights for governments and corporations based on historical data and trend analysis.", kd_service2_title: "Geopolitical Analysis", kd_service2_desc: "Offering in-depth risk analysis and forecasting for international operations and investments.", kd_service3_title: "Archive Management", kd_service3_desc: "Digitalization and management of governmental and corporate historical archives.",
        form_title: "Request an Appointment", form_name: "Name", form_surname: "Surname", form_email: "Email Address", form_phone: "Phone Number (Optional)", form_country: "Country of Operation", form_city: "City", form_submit: "Send Request", form_message: "Your Message",
        pep_page_title: "PeP - Digital Financial Freedom", pep_intro: "PeP (Palladium Electronic Money), a KyroServices Global brand, is a reliable electronic money institution licensed by the BRSA and supervised by the Central Bank of the Republic of Turkey. It offers solutions for the modern financial world.", pep_features_title: "Key Features & Advantages", pep_feature1: "<strong>Multi-Currency Support:</strong> Manage accounts in TRY, EUR, GBP, USD and more from a single app.", pep_feature2: "<strong>Low-Cost International Transfers:</strong> Easily send and receive money internationally with minimal fees.", pep_feature3: "<strong>PeP Visa Cards:</strong> Secure virtual cards for online shopping and physical cards valid at ATMs and POS terminals worldwide.", pep_feature4: "<strong>Precious Metal Investment:</strong> Easily open Gold, Silver, and Platinum accounts through the app.", pep_contact_button: "Contact Support",
        yunan_page_title: "Yunandan Gelsin - Flavors of the Aegean", yunan_intro: "A brand of KyroServices Global, Yunandan Gelsin brings the most authentic and traditional flavors of Greece to Turkey. We carefully select each product to deliver a genuine Aegean experience.", yunan_stores_title: "Our Stores", yunan_online_title: "Shop Online", yunan_online_text: "To access all our products and shop from anywhere in Turkey, visit our e-commerce platform.", yunan_online_button: "Visit Online Store",
        kampus_page_title: "Kampüs Giyim - We Dress Your Identity", kampus_intro: "Kampüs Giyim, a KyroServices Global company, is a leading provider of custom apparel and promotional products for universities, schools, sports teams, and corporations. With our state-of-the-art DesignLab and commitment to quality, we bring your identity to life.", kampus_clients_title: "Who We Serve", kampus_client1: "Educational Institutions (Universities, High Schools)", kampus_client2: "Sports Clubs and Teams", kampus_client3: "Corporations and NGOs", kampus_client4: "Events and Private Groups", kampus_products_title: "Our Product Range", kampus_product_list: "T-shirts, sweatshirts, hoodies, caps, tote bags, mugs, and a wide range of stationery products.", kampus_form_title: "Request a Bulk Order Quote",
        rezi_page_title: "ReziKyros - Building with Trust", rezi_intro: "As the construction and real estate development brand of KyroServices Global, ReziKyros operates in Turkey and Europe with a core philosophy: building reliable, high-quality, and solid structures. We don't just build buildings; we build lasting trust.", rezi_philosophy_title: "Our Philosophy", rezi_philosophy_text: "Our foundation is built on three pillars: architectural excellence, unwavering quality in materials and craftsmanship, and creating lasting value for our investors and residents.", rezi_activity_title: "Our Fields of Activity", rezi_activity1: "Luxury Residential Projects", rezi_activity2: "Commercial Real Estate Solutions", rezi_activity3: "Urban Renewal Projects", rezi_form_title: "Discuss Your Project",
        kosmos_page_title: "Kosmos Vize - Your Gateway to Greece", kosmos_intro: "As a KyroServices Global company, Kosmos Vize is the sole visa application center officially authorized by the Consulate of Greece in Turkey. We have been providing reliable and efficient visa services since 2012.", kosmos_legal_title: "Legal Status & Assurance", kosmos_legal_text: "Kosmos Vize is officially authorized by the Embassy of Greece in Ankara and the Consulate General in Istanbul. We accept applications for Greece visas only. The evaluation and final decision on applications are made exclusively by the Greek Consular authorities.", kosmos_services_title: "Our Services", kosmos_service1: "Schengen Visa Applications (up to 90 days)", kosmos_service2: "National Visa Applications (more than 90 days)", kosmos_service3: "Appointment Scheduling System", kosmos_service4: "Application Tracking", kosmos_offices_title: "Our Offices",
        thank_you_title: "Thank You!", thank_you_text: "Your request has been successfully received. We will contact you as soon as possible.", back_home: "Back to Home",
        page_not_found: "Page Not Found", page_not_found_text: "The page you are looking for might have been removed or is temporarily unavailable.",
        privacy_policy: "Privacy Policy",
    },
    tr: {
        slogan: "Avrupa'nın Gücü", aboutTitle: "Hakkımızda", aboutParagraph: "Merkezi Atina, Yunanistan'da bulunan KyroServices Global, tüm Avrupa ve Türkiye'de faaliyet gösteren dinamik bir çatı şirkettir. Çok çeşitli sektörlerde mükemmellik ve yenilik sunarak farklı uzmanlaşmış markalardan oluşan bir portföyü yönetiyoruz.", address: "Leoforos Kifisias 123, Marousi, 151 24 Atina, Yunanistan", brandsTitle: "Markalarımız ve Operasyonlarımız", opsTurkeyTitle: "Franchise Operasyonları", opsTurkeyParagraph: "2 Burger King (Vadi İstanbul, Bodrum) şubesi ve Bodrum bölgesindeki tüm Starbucks mağazaları tarafımızca işletilmektedir.", teamTitle: "Yönetim Kurulu", team_kyros_name: "Kyros I. DUGAN", team_kyros_title: "Kurucu Sahip", team_alissa_name: "Alissa KIRAKIS", team_alissa_title: "KyroServices Global Genel Direktörü", team_gamze_name: "Gamze ÖZDEN", team_gamze_title: "KyroServices Türkiye & Yunandan Gelsin Genel Direktörü", team_dimitri_name: "Dimitri LYANOS", team_dimitri_title: "K&D History Services Avrupa & ABD Genel Direktörü", team_beyza_name: "Beyza ÇİMEN", team_beyza_title: "K&D History Services Türkiye Genel Direktörü", team_sadio_name: "Mehmet Sadioğlu", team_sadio_title: "PeP Genel Müdürü", team_fatma_name: "Fatma BAYSAN", team_fatma_title: "Kosmos Vize Genel Müdürü", team_fevzi_name: "Fevzi Cem İz", team_fevzi_title: "Kampüs Giyim Genel Müdürü", team_tugce_name: "Müh. Tuğçe SARICA", team_tugce_title: "ReziKyros Genel Müdürü", team_hande_name: "Hande DERİN", team_hande_title: "Burger King & Starbucks Franchise Gn. Koordinatörü", strategyTitle: "Stratejik Vizyonumuz", strategyParagraph: "Vizyonumuz, farklı markalarımız arasında sinerji yaratarak inovasyonu ve sürdürülebilir büyümeyi teşvik etmektir. Müşterilerimize ve ortaklarımıza dünya çapında olağanüstü değer sunarken, mükemmelliğe ve küresel ayak izimizi genişletmeye kararlıyız.", contactTitle: "Bize Ulaşın", contactSubtitle: "Projeleriniz ve iş birlikleriniz için bize ulaşmaktan çekinmeyin.", contactButton: "Bize Ulaşın",
        menu_home: "Ana Sayfa", menu_about: "Hakkımızda", menu_team: "Yönetim", menu_brands: "Markalarımız", menu_career: "Kariyer", menu_contact: "İletişim", menu_kd: "K&D History Services", menu_pep: "PeP", menu_yunan: "Yunandan Gelsin", menu_kampus: "Kampüs Giyim", menu_rezi: "ReziKyros", menu_kosmos: "Kosmos Vize",
        brand_desc_kd: "Resmi NATO partneri olarak 12 ülkede tarihsel danışmanlık ve jeopolitik analiz hizmetleri sunar.", brand_desc_pep: "TCMB denetiminde, uluslararası para transferi ve dijital cüzdan çözümleri sunan bir elektronik para kuruluşu.", brand_desc_yunan: "Yunanistan'ın otantik ve geleneksel ürünlerini, Türkiye'deki mağazaları ve e-ticaret platformuyla tüketicilere sunar.", brand_desc_kampus: "Okullar, spor takımları ve şirketler için kişiselleştirilebilir, tasarım odaklı giyim ve tanıtım ürünleri üretir.", brand_desc_rezi: "Türkiye ve Avrupa'da, güven ve kalite odaklı, yüksek standartlarda lüks konut ve ticari inşaat projeleri geliştirir.", brand_desc_kosmos: "Türkiye'deki tek resmi Yunanistan Konsolosluğu yetkili vize başvuru merkezi olarak Schengen ve ulusal vize hizmetleri sunar.",
        about_page_title: "KyroServices Global Hakkında", about_section1_title: "Hikayemiz ve Vizyonumuz", about_section1_p1: "KyroServices Global, kurucumuz Kyros I. Dugan'ın vizyonuyla, sadece farklı sektörlerde faaliyet gösteren bir şirketler topluluğu olmakla kalmayıp, aynı zamanda Avrupa ve Türkiye arasında ekonomik ve kültürel bir köprü kurma amacıyla 2012 yılında Atina'da kurulmuştur. Tarihin derinliklerinden aldığı ilhamı geleceğin teknolojileriyle birleştiren şirketimiz, en başından beri her girdiği sektörde standartları yeniden belirlemeyi hedeflemiştir.", about_section1_p2: "Başlangıçta tarihsel danışmanlık ve vize hizmetleri gibi niş alanlarda başlayan yolculuğumuz, kısa sürede tekstil, gıda, inşaat ve finansal teknolojiler gibi geniş bir yelpazeye yayılarak uluslararası bir güç haline gelmiştir.", about_section2_title: "Misyonumuz ve Değerlerimiz", about_section2_p1: "Misyonumuz, çatımız altındaki her bir markanın kendi alanında lider olmasını sağlarken, tüm grup şirketleri arasında bir sinerji yaratarak sürdürülebilir ve yenilikçi bir büyüme modeli oluşturmaktır. Müşteri memnuniyetini ve kaliteyi her şeyin üzerinde tutarız.", value1: "<strong>Kalite:</strong> Sunduğumuz her ürün ve hizmette en yüksek standartları hedefleriz.", value2: "<strong>Güven:</strong> Tüm paydaşlarımızla ilişkilerimizi şeffaflık ve dürüstlük üzerine kurarız.", value3: "<strong>İnovasyon:</strong> Statükoya meydan okur, sektörlerimize yön veren yenilikçi çözümler geliştiririz.", value4: "<strong>Global Bakış Açısı:</strong> Yerel değerlere saygı duyarak küresel ölçekte düşünür ve hareket ederiz.",
        team_page_title: "Yönetim Kurulu", team_kyros_bio: "KyroServices Global'in vizyoner kurucusu; grubu, tarihsel derinliği geleceğe yönelik stratejilerle harmanlayan benzersiz bir bakış açısıyla yönetmektedir.", team_alissa_bio: "Grubun genel küresel operasyonlarını ve stratejik yönünü yöneterek tüm markalar arasında sinerji ve büyümeyi sağlar.", team_gamze_bio: "Dinamik Türkiye pazarındaki operasyonları yönetir ve aynı zamanda iki kültür arasında köprü kuran 'Yunandan Gelsin' markasını yönetir.", team_dimitri_bio: "Avrupa ve ABD'deki tarihsel danışmanlık hizmetlerine liderlik ederek hükümetlere ve kuruluşlara kritik bilgiler sunar.", team_beyza_bio: "K&D History Services'in Türkiye operasyonlarını yöneterek küresel uzmanlığı yerel tarihsel bağlama uyarlar.", team_sadio_bio: "Dijital ödeme alanındaki genişlemesini sürdüren yenilikçi finansal teknoloji markası PeP'e liderlik eder.", team_fatma_bio: "Türkiye'deki tek resmi Yunanistan vize başvuru merkezi olan Kosmos Vize'yi yöneterek kusursuz hizmet sağlar.", team_fevzi_bio: "Eğitim ve kurumsal müşterilere özel giyim sağlama odaklı Kampüs Giyim markasını yönetir.", team_tugce_bio: "Yüksek kaliteli, güvenilir gayrimenkul projeleri geliştirmeye odaklanan ReziKyros inşaat markasına liderlik eder.", team_hande_bio: "Burger King & Starbucks franchise'larının başarılı operasyonunu koordine ederek yüksek kalite ve hizmet standartlarını korur.",
        career_page_title: "KyroServices Global'de Kariyer", career_section1_title: "Ailemize Katılın", career_section1_p1: "KyroServices Global'de en büyük değerimiz insan kaynağımızdır. Her ekip üyemizin değer gördüğü ve büyüme fırsatı bulduğu, destekleyici, iş birliğine dayalı ve dinamik bir çalışma ortamı yaratıyoruz. Başarıyı birlikte inşa eden, hem bireysel hem de ortak başarıları kutlayan bir aileyiz.", career_section2_title: "Sunduklarımız", career_section2_p1: "Çalışanlarımıza rekabetçi bir ücretlendirme paketi, kapsamlı yan haklar ve sürekli mesleki gelişim fırsatları sunuyoruz. Ekibimizin gelişimine yatırım yapıyoruz çünkü şirketimizin başarısının, çalışanlarımızın uzmanlığı ve tutkusu üzerine kurulu olduğunu biliyoruz.", career_section3_title: "Genel Başvuru", career_section3_p1: "Ekibimize katılacak yetenekli ve tutkulu kişileri her zaman arıyoruz. Başarımıza katkıda bulunabileceğinize inanıyorsanız, lütfen özgeçmişinizi İnsan Kaynakları departmanımıza gönderin.",
        contact_page_title: "Bize Ulaşın", contact_greece_title: "Global Merkez (Atina)", contact_turkey_title: "Türkiye Genel Müdürlük (İstanbul)", contact_form_title: "Bize Mesaj Gönderin",
        kd_presence_title: "Global Varlık", kd_presence_text: "<strong>12 ülkede 73 ofis</strong> ile faaliyet gösteren ağımız, uzmanlığımızın ve güvenilir ortaklıklarımızın bir kanıtıdır.", kd_partner_title: "NATO Partneri", kd_partner_text: "Kritik tarihsel ve jeopolitik danışmanlık sağlayan bir <strong>Resmi NATO Partneri</strong> olmaktan gurur duyuyoruz.",
        kd_expertise_title: "Uzmanlık Alanlarımız", kd_service1_title: "Tarihsel Danışmanlık", kd_service1_desc: "Tarihsel verilere ve trend analizlerine dayanarak hükümetler ve şirketler için stratejik öngörüler sağlama.", kd_service2_title: "Jeopolitik Analiz", kd_service2_desc: "Uluslararası operasyonlar ve yatırımlar için derinlemesine risk analizi ve tahminler sunma.", kd_service3_title: "Arşiv Yönetimi", kd_service3_desc: "Hükümet ve şirketlerin tarihsel arşivlerinin dijitalleştirilmesi ve yönetimi.",
        form_title: "Randevu Talep Edin", form_name: "Ad", form_surname: "Soyad", form_email: "E-posta Adresi", form_phone: "Telefon Numarası (İsteğe Bağlı)", form_country: "Operasyon Ülkesi", form_city: "Şehir", form_submit: "Talebi Gönder", form_message: "Mesajınız",
        pep_page_title: "PeP - Finansal Özgürlüğün Dijital Adı", pep_intro: "Bir KyroServices Global markası olan PeP (Paladyum Elektronik Para), BDDK lisanslı ve T.C. Merkez Bankası denetimindeki güvenilir bir elektronik para kuruluşudur. Modern finans dünyasının gerektirdiği çözümleri sunar.", pep_features_title: "Temel Özellikler ve Avantajlar", pep_feature1: "<strong>Çoklu Para Birimi Desteği:</strong> TL, EUR, GBP, USD ve daha birçok para biriminde hesabı tek uygulamadan yönetin.", pep_feature2: "<strong>Düşük Maliyetli Uluslararası Transfer:</strong> Yurt dışına kolayca ve düşük ücretlerle para gönderin, yurt dışından ödeme alın.", pep_feature3: "<strong>PeP Visa Kartlar:</strong> Online alışverişler için güvenli sanal kartlar ve dünya genelinde geçerli fiziksel kartlar.", pep_feature4: "<strong>Değerli Maden Yatırımı:</strong> Uygulama üzerinden kolayca Altın, Gümüş ve Platin hesabı açarak yatırım yapın.", pep_contact_button: "Destek için İletişime Geçin",
        yunan_page_title: "Yunandan Gelsin - Ege'nin Lezzetleri Kapınızda", yunan_intro: "Bir KyroServices Global markası olan Yunandan Gelsin, Yunanistan'ın en otantik ve geleneksel lezzetlerini Türkiye'ye taşıyor. Gerçek bir Ege deneyimi sunmak için her ürünümüzü özenle seçiyoruz.", yunan_stores_title: "Mağazalarımız", yunan_online_title: "Online Alışveriş", yunan_online_text: "Tüm ürünlerimize erişmek ve Türkiye'nin her yerinden alışveriş yapmak için e-ticaret platformumuzu ziyaret edin.", yunan_online_button: "Online Mağazayı Ziyaret Et",
        kampus_page_title: "Kampüs Giyim - Kimliğinizi Giydiriyoruz", kampus_intro: "Bir KyroServices Global şirketi olan Kampüs Giyim, üniversiteler, okullar, spor takımları ve şirketler için özel giyim ve tanıtım ürünleri alanında lider bir sağlayıcıdır. Gelişmiş DesignLab aracımız ve kaliteye olan bağlılığımızla kimliğinizi hayata geçiriyoruz.", kampus_clients_title: "Kime Hizmet Ediyoruz?", kampus_client1: "Eğitim Kurumları (Üniversiteler, Liseler)", kampus_client2: "Spor Kulüpleri ve Takımları", kampus_client3: "Şirketler ve Sivil Toplum Kuruluşları", kampus_client4: "Etkinlikler ve Özel Gruplar", kampus_products_title: "Ürün Yelpazemiz", kampus_product_list: "T-shirt, sweatshirt, hoodie, şapka, bez çanta, kupa ve geniş bir yelpazede kırtasiye ürünleri.", kampus_form_title: "Toplu Sipariş Teklifi Alın",
        rezi_page_title: "ReziKyros - Güvenle İnşa Ediyoruz", rezi_intro: "KyroServices Global'in inşaat ve gayrimenkul geliştirme markası olan ReziKyros, Türkiye ve Avrupa'da temel bir felsefeyle faaliyet gösterir: güvenilir, kaliteli ve sağlam yapılar inşa etmek. Biz sadece binalar inşa etmiyoruz; kalıcı bir güven inşa ediyoruz.", rezi_philosophy_title: "Felsefemiz", rezi_philosophy_text: "Temelimiz üç sütun üzerine kuruludur: mimari mükemmellik, malzeme ve işçilikte sarsılmaz kalite ve yatırımcılarımız ile sakinlerimiz için kalıcı değer yaratmak.", rezi_activity_title: "Faaliyet Alanlarımız", rezi_activity1: "Lüks Konut Projeleri", rezi_activity2: "Ticari Gayrimenkul Çözümleri", rezi_activity3: "Kentsel Dönüşüm Projeleri", rezi_form_title: "Projenizi Görüşelim",
        kosmos_page_title: "Kosmos Vize - Yunanistan'a Açılan Kapınız", kosmos_intro: "Bir KyroServices Global şirketi olan Kosmos Vize, Türkiye'de Yunanistan Konsolosluğu tarafından resmi olarak yetkilendirilmiş tek vize başvuru merkezidir. 2012'den beri güvenilir ve verimli vize hizmetleri sunmaktayız.", kosmos_legal_title: "Yasal Statü ve Güvence", kosmos_legal_text: "Kosmos Vize, Yunanistan Ankara Büyükelçiliği ve İstanbul Başkonsolosluğu tarafından resmen yetkilendirilmiştir. Sadece Yunanistan vizesi başvurularını kabul eder. Başvuruların değerlendirilmesi ve sonuçlandırılması münhasıran Yunan Konsolosluk makamları tarafından yapılır.", kosmos_services_title: "Hizmetlerimiz", kosmos_service1: "Schengen Vize Başvuruları (90 güne kadar)", kosmos_service2: "Ulusal Vize Başvuruları (90 günden uzun)", kosmos_service3: "Randevu Takip Sistemi", kosmos_service4: "Başvuru Takibi", kosmos_offices_title: "Ofislerimiz",
        thank_you_title: "Teşekkür Ederiz!", thank_you_text: "Mesajınız başarıyla alınmıştır. En kısa sürede sizinle iletişime geçeceğiz.", back_home: "Ana Sayfaya Dön",
        page_not_found: "Sayfa Bulunamadı", page_not_found_text: "Aradığınız sayfa kaldırılmış veya geçici olarak kullanılamıyor olabilir.",
        privacy_policy: "Gizlilik Politikası",
    },
    el: {
    slogan: "Η Δύναμη της Ευρώπης", aboutTitle: "Σχετικά με εμάς", aboutParagraph: "Με έδρα την Αθήνα, Ελλάδα, η KyroServices Global είναι μια δυναμική μητρική εταιρεία που δραστηριοποιείται σε όλη την Ευρώπη και την Τουρκία. Διαχειριζόμαστε ένα ποικίλο χαρτοφυλάκιο εξειδικευμένων εμπορικών σημάτων, προσφέροντας αριστεία και καινοτομία σε ένα ευρύ φάσμα κλάδων.", address: "Λεωφόρος Κηφισίας 123, Μαρούσι, 151 24 Αθήνα, Ελλάδα", brandsTitle: "Οι Μάρκες & οι Δραστηριότητές μας", opsTurkeyTitle: "Δραστηριότητες Franchise", opsTurkeyParagraph: "2 υποκαταστήματα Burger King (Vadi Istanbul, Bodrum) και όλα τα καταστήματα Starbucks στην περιοχή της Αλικαρνασσού λειτουργούν υπό τη διαχείρισή μας.", teamTitle: "Το Διοικητικό μας Συμβούλιο", team_kyros_name: "Kyros I. DUGAN", team_kyros_title: "Ιδρυτής & Ιδιοκτήτης", team_alissa_name: "Alissa KIRAKIS", team_alissa_title: "Γενική Διευθύντρια, KyroServices Global", team_gamze_name: "Gamze ÖZDEN", team_gamze_title: "Γενική Διευθύντρια, KyroServices Turkey & Yunandan Gelsin", team_dimitri_name: "Dimitri LYANOS", team_dimitri_title: "Γενικός Διευθυντής, K&D History Services Ευρώπης & ΗΠΑ", team_beyza_name: "Beyza ÇİMEN", team_beyza_title: "Γενική Διευθύντρια, K&D History Services Τουρκίας", team_sadio_name: "Mehmet Sadioğlu", team_sadio_title: "Γενικός Διευθυντής, PeP", team_fatma_name: "Fatma BAYSAN", team_fatma_title: "Γενική Διευθύντρια, Kosmos Vize", team_fevzi_name: "Fevzi Cem İz", team_fevzi_title: "Γενικός Διευθυντής, Kampüs Giyim", team_tugce_name: "Müh. Tuğçe SARICA", team_tugce_title: "Γενική Διευθύντρια, ReziKyros", team_hande_name: "Hande DERİN", team_hande_title: "Γενική Συντονίστρια, Burger King & Starbucks Franchises", strategyTitle: "Το Στρατηγικό μας Όραμα", strategyParagraph: "Το όραμά μας είναι να προωθήσουμε τη συνέργεια μεταξύ των διαφόρων εμπορικών σημάτων μας, οδηγώντας στην καινοτομία και τη βιώσιμη ανάπτυξη. Δεσμευόμαστε στην αριστεία και στην επέκταση του παγκόσμιου αποτυπώματός μας, προσφέροντας εξαιρετική αξία στους πελάτες και τους συνεργάτες μας παγκοσμίως.", contactTitle: "Επικοινωνήστε μαζί μας", contactSubtitle: "Μη διστάσετε να επικοινωνήσετε μαζί μας για έργα και συνεργασίες.", contactButton: "Επικοινωνήστε μαζί μας",
    menu_home: "Αρχική", menu_about: "Σχετικά με εμάς", menu_team: "Διοίκηση", menu_brands: "Οι Μάρκες μας", menu_career: "Καριέρα", menu_contact: "Επικοινωνία", menu_kd: "K&D History Services", menu_pep: "PeP", menu_yunan: "Yunandan Gelsin", menu_kampus: "Kampüs Giyim", menu_rezi: "ReziKyros", menu_kosmos: "Kosmos Vize",
    brand_desc_kd: "Ως επίσημος εταίρος του ΝΑΤΟ, παρέχει υπηρεσίες ιστορικής συμβουλευτικής και γεωπολιτικής ανάλυσης σε 12 χώρες.", brand_desc_pep: "Ένα ίδρυμα ηλεκτρονικού χρήματος υπό την εποπτεία της Κεντρικής Τράπεζας της Τουρκίας, που προσφέρει διεθνείς μεταφορές χρημάτων και λύσεις ψηφιακού πορτοφολιού.", brand_desc_yunan: "Παρουσιάζει αυθεντικά και παραδοσιακά προϊόντα της Ελλάδας στους καταναλωτές μέσω των καταστημάτων της στην Τουρκία και της πλατφόρμας ηλεκτρονικού εμπορίου της.", brand_desc_kampus: "Παράγει προσαρμόσιμα, σχεδιαστικά ενδύματα και διαφημιστικά προϊόντα για σχολεία, αθλητικές ομάδες και εταιρείες.", brand_desc_rezi: "Αναπτύσσει υψηλών προδιαγραφών πολυτελή οικιστικά και εμπορικά κατασκευαστικά έργα στην Τουρκία και την Ευρώπη με έμφαση στην εμπιστοσύνη και την ποιότητα.", brand_desc_kosmos: "Ως το μοναδικό επίσημα εξουσιοδοτημένο κέντρο υποβολής αιτήσεων θεώρησης για το Προξενείο της Ελλάδας στην Τουρκία, προσφέρει υπηρεσίες για θεωρήσεις Σένγκεν και εθνικές θεωρήσεις.",
    about_page_title: "Σχετικά με την KyroServices Global", about_section1_title: "Η Ιστορία & το Όραμά μας", about_section1_p1: "Η KyroServices Global ιδρύθηκε στην Αθήνα το 2012 με το όραμα του ιδρυτή μας, Kyros I. Dugan, όχι μόνο να είναι ένας όμιλος εταιρειών που δραστηριοποιείται σε διάφορους τομείς, αλλά και να χτίσει μια οικονομική και πολιτιστική γέφυρα μεταξύ Ευρώπης και Τουρκίας. Συνδυάζοντας την έμπνευση από τα βάθη της ιστορίας με τις τεχνολογίες του μέλλοντος, η εταιρεία μας έχει ως στόχο να επαναπροσδιορίσει τα πρότυπα σε κάθε τομέα που εισέρχεται από την ίδρυσή της.", about_section1_p2: "Το ταξίδι μας, το οποίο αρχικά ξεκίνησε σε εξειδικευμένους τομείς όπως η ιστορική συμβουλευτική και οι υπηρεσίες έκδοσης θεωρήσεων, επεκτάθηκε γρήγορα σε ένα ευρύ φάσμα πεδίων, συμπεριλαμβανομένων των κλωστοϋφαντουργικών προϊόντων, των τροφίμων, των κατασκευών και των χρηματοοικονομικών τεχνολογιών, καθιστώντας μας μια διεθνή δύναμη.", about_section2_title: "Η Αποστολή & οι Αξίες μας", about_section2_p1: "Η αποστολή μας είναι να δημιουργήσουμε ένα βιώσιμο και καινοτόμο μοντέλο ανάπτυξης, δημιουργώντας συνέργειες μεταξύ όλων των εταιρειών του ομίλου μας, διασφαλίζοντας παράλληλα ότι κάθε μία από τις μάρκες μας είναι ηγέτης στον τομέα της. Τοποθετούμε την ικανοποίηση των πελατών και την ποιότητα πάνω από όλα.", value1: "<strong>Ποιότητα:</strong> Στοχεύουμε στα υψηλότερα πρότυπα σε κάθε προϊόν και υπηρεσία που προσφέρουμε.", value2: "<strong>Εμπιστοσύνη:</strong> Χτίζουμε τις σχέσεις μας με όλους τους ενδιαφερόμενους σε διαφάνεια και ειλικρίνεια.", value3: "<strong>Καινοτομία:</strong> Αμφισβητούμε το κατεστημένο και αναπτύσσουμε καινοτόμες λύσεις που διαμορφώνουν τους κλάδους μας.", value4: "<strong>Παγκόσμια Προοπτική:</strong> Σκεφτόμαστε και δρούμε σε παγκόσμια κλίμακα, σεβόμενοι τις τοπικές αξίες.",
    team_page_title: "Το Διοικητικό μας Συμβούλιο", team_kyros_bio: "Ο οραματιστής ιδρυτής της KyroServices Global, που καθοδηγεί τον όμιλο με μια μοναδική προοπτική που συνδυάζει το ιστορικό βάθος με στρατηγικές προσανατολισμένες στο μέλλον.", team_alissa_bio: "Διαχειρίζεται τις συνολικές παγκόσμιες δραστηριότητες και τη στρατηγική κατεύθυνση του ομίλου, διασφαλίζοντας συνέργεια και ανάπτυξη σε όλες τις μάρκες.", team_gamze_bio: "Ηγείται των δραστηριοτήτων στη δυναμική τουρκική αγορά και διευθύνει επίσης τη μάρκα «Yunandan Gelsin», γεφυρώνοντας δύο πολιτισμούς.", team_dimitri_bio: "Επικεφαλής των υπηρεσιών ιστορικής συμβουλευτικής σε όλη την Ευρώπη και τις ΗΠΑ, παρέχοντας κρίσιμες γνώσεις σε κυβερνήσεις και οργανισμούς.", team_beyza_bio: "Διευθύνει τις τουρκικές δραστηριότητες της K&D History Services, προσαρμόζοντας την παγκόσμια εμπειρογνωμοσύνη στο τοπικό ιστορικό πλαίσιο.", team_sadio_bio: "Ηγείται της καινοτόμου μάρκας χρηματοοικονομικής τεχνολογίας PeP, οδηγώντας την επέκτασή της στο τοπίο των ψηφιακών πληρωμών.", team_fatma_bio: "Διαχειρίζεται την Kosmos Vize, το μοναδικό επίσημο κέντρο υποβολής αιτήσεων θεώρησης για την Ελλάδα στην Τουρκία, διασφαλίζοντας απρόσκοπτη εξυπηρέτηση.", team_fevzi_bio: "Διευθύνει τη μάρκα Kampüs Giyim, εστιάζοντας στην παροχή εξατομικευμένων ενδυμάτων για εκπαιδευτικούς και εταιρικούς πελάτες.", team_tugce_bio: "Ηγείται της κατασκευαστικής μάρκας ReziKyros, εστιάζοντας στην ανάπτυξη υψηλής ποιότητας, αξιόπιστων κτηματομεσιτικών έργων.", team_hande_bio: "Συντονίζει την επιτυχημένη λειτουργία των franchises Burger King και Starbucks, διατηρώντας υψηλά πρότυπα ποιότητας και εξυπηρέτησης.",
    career_page_title: "Καριέρα στην KyroServices Global", career_section1_title: "Γίνετε μέλος της οικογένειάς μας", career_section1_p1: "Στην KyroServices Global, πιστεύουμε ότι το μεγαλύτερο περιουσιακό μας στοιχείο είναι οι άνθρωποί μας. Προωθούμε ένα υποστηρικτικό, συνεργατικό και δυναμικό περιβάλλον εργασίας όπου κάθε μέλος της ομάδας εκτιμάται και έχει την ευκαιρία να αναπτυχθεί. Είμαστε μια οικογένεια που χτίζει την επιτυχία μαζί, γιορτάζοντας τόσο τα ατομικά όσο και τα συλλογικά επιτεύγματα.", career_section2_title: "Τι προσφέρουμε", career_section2_p1: "Παρέχουμε στους υπαλλήλους μας ένα ανταγωνιστικό πακέτο αποδοχών, ολοκληρωμένες παροχές και συνεχείς ευκαιρίες για επαγγελματική ανάπτυξη. Επενδύουμε στην ανάπτυξη της ομάδας μας γιατί γνωρίζουμε ότι η επιτυχία της εταιρείας μας βασίζεται στην τεχνογνωσία και το πάθος των υπαλλήλων μας.", career_section3_title: "Γενική Αίτηση", career_section3_p1: "Αναζητούμε πάντα ταλαντούχα και παθιασμένα άτομα για να ενταχθούν στην ομάδα μας. Εάν πιστεύετε ότι έχετε ό,τι χρειάζεται για να συμβάλετε στην επιτυχία μας, στείλτε το βιογραφικό σας στο τμήμα Ανθρώπινου Δυναμικού.",
    contact_page_title: "Επικοινωνήστε μαζί μας", contact_greece_title: "Παγκόσμια Έδρα (Αθήνα)", contact_turkey_title: "Έδρα Τουρκίας (Κωνσταντινούπολη)", contact_form_title: "Στείλτε μας μήνυμα",
    kd_presence_title: "Παγκόσμια Παρουσία", kd_presence_text: "Λειτουργώντας με <strong>73 γραφεία σε 12 χώρες</strong>, η εμβέλειά μας αποτελεί απόδειξη της τεχνογνωσίας και των αξιόπιστων συνεργασιών μας.", kd_partner_title: "Εταίρος του ΝΑΤΟ", kd_partner_text: "Είμαστε περήφανοι που είμαστε <strong>Επίσημος Εταίρος του ΝΑΤΟ</strong>, παρέχοντας κρίσιμες ιστορικές και γεωπολιτικές συμβουλές.",
    kd_expertise_title: "Η Εξειδίκευσή μας", kd_service1_title: "Ιστορική Συμβουλευτική", kd_service1_desc: "Παροχή στρατηγικών γνώσεων σε κυβερνήσεις και εταιρείες βάσει ιστορικών δεδομένων και ανάλυσης τάσεων.", kd_service2_title: "Γεωπολιτική Ανάλυση", kd_service2_desc: "Προσφορά εις βάθος ανάλυσης κινδύνου και προβλέψεων για διεθνείς επιχειρήσεις και επενδύσεις.", kd_service3_title: "Διαχείριση Αρχείων", kd_service3_desc: "Ψηφιοποίηση και διαχείριση κυβερνητικών και εταιρικών ιστορικών αρχείων.",
    form_title: "Αίτηση Ραντεβού", form_name: "Όνομα", form_surname: "Επώνυμο", form_email: "Διεύθυνση Email", form_phone: "Αριθμός Τηλεφώνου (Προαιρετικό)", form_country: "Χώρα Επιχείρησης", form_city: "Πόλη", form_submit: "Αποστολή Αιτήματος", form_message: "Το μήνυμά σας",
    pep_page_title: "PeP - Ψηφιακή Οικονομική Ελευθερία", pep_intro: "Η PeP (Palladium Electronic Money), μια μάρκα της KyroServices Global, είναι ένα αξιόπιστο ίδρυμα ηλεκτρονικού χρήματος με άδεια από την BRSA και υπό την εποπτεία της Κεντρικής Τράπεζας της Δημοκρατίας της Τουρκίας. Προσφέρει λύσεις για τον σύγχρονο χρηματοοικονομικό κόσμο.", pep_features_title: "Βασικά Χαρακτηριστικά & Πλεονεκτήματα", pep_feature1: "<strong>Υποστήριξη πολλαπλών νομισμάτων:</strong> Διαχειριστείτε λογαριασμούς σε TRY, EUR, GBP, USD και άλλα από μία μόνο εφαρμογή.", pep_feature2: "<strong>Διεθνείς μεταφορές χαμηλού κόστους:</strong> Στείλτε και λάβετε χρήματα διεθνώς εύκολα με ελάχιστες χρεώσεις.", pep_feature3: "<strong>Κάρτες PeP Visa:</strong> Ασφαλείς εικονικές κάρτες για ηλεκτρονικές αγορές και φυσικές κάρτες που ισχύουν σε ΑΤΜ και τερματικά POS παγκοσμίως.", pep_feature4: "<strong>Επένδυση σε πολύτιμα μέταλλα:</strong> Ανοίξτε εύκολα λογαριασμούς Χρυσού, Αργύρου και Πλατίνας μέσω της εφαρμογής.", pep_contact_button: "Επικοινωνήστε με την Υποστήριξη",
    yunan_page_title: "Yunandan Gelsin - Γεύσεις του Αιγαίου", yunan_intro: "Μια μάρκα της KyroServices Global, η Yunandan Gelsin φέρνει τις πιο αυθεντικές και παραδοσιακές γεύσεις της Ελλάδας στην Τουρκία. Επιλέγουμε προσεκτικά κάθε προϊόν για να προσφέρουμε μια γνήσια εμπειρία Αιγαίου.", yunan_stores_title: "Τα Καταστήματά μας", yunan_online_title: "Αγορές Online", yunan_online_text: "Για να αποκτήσετε πρόσβαση σε όλα τα προϊόντα μας και να ψωνίσετε από οπουδήποτε στην Τουρκία, επισκεφθείτε την πλατφόρμα ηλεκτρονικού εμπορίου μας.", yunan_online_button: "Επισκεφθείτε το Online Κατάστημα",
    kampus_page_title: "Kampüs Giyim - Ντύνουμε την ταυτότητά σας", kampus_intro: "Η Kampüs Giyim, μια εταιρεία της KyroServices Global, είναι κορυφαίος πάροχος προσαρμοσμένων ενδυμάτων και διαφημιστικών προϊόντων για πανεπιστήμια, σχολεία, αθλητικές ομάδες και εταιρείες. Με το υπερσύγχρονο DesignLab και τη δέσμευσή μας στην ποιότητα, δίνουμε ζωή στην ταυτότητά σας.", kampus_clients_title: "Ποιούς εξυπηρετούμε", kampus_client1: "Εκπαιδευτικά Ιδρύματα (Πανεπιστήμια, Λύκεια)", kampus_client2: "Αθλητικοί Σύλλογοι και Ομάδες", kampus_client3: "Εταιρείες και ΜΚΟ", kampus_client4: "Εκδηλώσεις και Ιδιωτικές Ομάδες", kampus_products_title: "Η Γκάμα των Προϊόντων μας", kampus_product_list: "T-shirts, φούτερ, hoodies, καπέλα, πάνινες τσάντες, κούπες και μια μεγάλη ποικιλία ειδών γραφικής ύλης.", kampus_form_title: "Ζητήστε Προσφορά για Μαζική Παραγγελία",
    rezi_page_title: "ReziKyros - Χτίζοντας με Εμπιστοσύνη", rezi_intro: "Ως η μάρκα κατασκευών και ανάπτυξης ακινήτων της KyroServices Global, η ReziKyros δραστηριοποιείται στην Τουρκία και την Ευρώπη με μια βασική φιλοσοφία: την κατασκευή αξιόπιστων, υψηλής ποιότητας και στέρεων κατασκευών. Δεν χτίζουμε απλώς κτίρια· χτίζουμε διαρκή εμπιστοσύνη.", rezi_philosophy_title: "Η Φιλοσοφία μας", rezi_philosophy_text: "Το θεμέλιό μας βασίζεται σε τρεις πυλώνες: αρχιτεκτονική αριστεία, ακλόνητη ποιότητα στα υλικά και την κατασκευή, και δημιουργία διαρκούς αξίας για τους επενδυτές και τους κατοίκους μας.", rezi_activity_title: "Οι Τομείς Δραστηριότητάς μας", rezi_activity1: "Πολυτελή Οικιστικά Έργα", rezi_activity2: "Λύσεις Εμπορικών Ακινήτων", rezi_activity3: "Έργα Αστικής Ανάπλασης", rezi_form_title: "Συζητήστε το Έργο σας",
    kosmos_page_title: "Kosmos Vize - Η Πύλη σας προς την Ελλάδα", kosmos_intro: "Ως εταιρεία της KyroServices Global, η Kosmos Vize είναι το μοναδικό κέντρο υποβολής αιτήσεων θεώρησης που είναι επίσημα εξουσιοδοτημένο από το Προξενείο της Ελλάδας στην Τουρκία. Παρέχουμε αξιόπιστες και αποτελεσματικές υπηρεσίες θεώρησης από το 2012.", kosmos_legal_title: "Νομικό Καθεστώς & Διασφάλιση", kosmos_legal_text: "Η Kosmos Vize είναι επίσημα εξουσιοδοτημένη από την Πρεσβεία της Ελλάδας στην Άγκυρα και το Γενικό Προξενείο στην Κωνσταντινούπολη. Δεχόμαστε αιτήσεις μόνο για θεωρήσεις Ελλάδας. Η αξιολόγηση και η τελική απόφαση για τις αιτήσεις λαμβάνονται αποκλειστικά από τις ελληνικές προξενικές αρχές.", kosmos_services_title: "Οι Υπηρεσίες μας", kosmos_service1: "Αιτήσεις Θεώρησης Σένγκεν (έως 90 ημέρες)", kosmos_service2: "Αιτήσεις Εθνικής Θεώρησης (άνω των 90 ημερών)", kosmos_service3: "Σύστημα Προγραμματισμού Ραντεβού", kosmos_service4: "Παρακολούθηση Αίτησης", kosmos_offices_title: "Τα Γραφεία μας",
    thank_you_title: "Ευχαριστούμε!", thank_you_text: "Το αίτημά σας ελήφθη με επιτυχία. Θα επικοινωνήσουμε μαζί σας το συντομότερο δυνατό.", back_home: "Επιστροφή στην Αρχική",
    page_not_found: "Η Σελίδα δεν βρέθηκε", page_not_found_text: "Η σελίδα που αναζητάτε μπορεί να έχει αφαιρεθεί ή να είναι προσωρινά μη διαθέσιμη.",
    privacy_policy: "Πολιτική Απορρήτου"
},
    fr: {
    slogan: "La Puissance de l'Europe", aboutTitle: "À propos de nous", aboutParagraph: "Basée à Athènes, en Grèce, KyroServices Global est une société mère dynamique opérant à travers l'Europe et la Turquie. Nous gérons un portefeuille diversifié de marques spécialisées, offrant l'excellence et l'innovation dans un large éventail d'industries.", address: "Leoforos Kifisias 123, Marousi, 151 24 Athènes, Grèce", brandsTitle: "Nos Marques & Opérations", opsTurkeyTitle: "Opérations de Franchise", opsTurkeyParagraph: "2 succursales Burger King (Vadi Istanbul, Bodrum) et tous les magasins Starbucks de la région de Bodrum sont exploités par nos soins.", teamTitle: "Notre Conseil d'Administration", team_kyros_name: "Kyros I. DUGAN", team_kyros_title: "Fondateur & Propriétaire", team_alissa_name: "Alissa KIRAKIS", team_alissa_title: "Directrice Générale, KyroServices Global", team_gamze_name: "Gamze ÖZDEN", team_gamze_title: "Directrice Générale, KyroServices Turquie & Yunandan Gelsin", team_dimitri_name: "Dimitri LYANOS", team_dimitri_title: "Directeur Général, K&D History Services Europe & USA", team_beyza_name: "Beyza ÇİMEN", team_beyza_title: "Directrice Générale, K&D History Services Turquie", team_sadio_name: "Mehmet Sadioğlu", team_sadio_title: "Directeur Général, PeP", team_fatma_name: "Fatma BAYSAN", team_fatma_title: "Directrice Générale, Kosmos Vize", team_fevzi_name: "Fevzi Cem İz", team_fevzi_title: "Directeur Général, Kampüs Giyim", team_tugce_name: "Müh. Tuğçe SARICA", team_tugce_title: "Directrice Générale, ReziKyros", team_hande_name: "Hande DERİN", team_hande_title: "Coordinatrice Générale, Franchises Burger King & Starbucks", strategyTitle: "Notre Vision Stratégique", strategyParagraph: "Notre vision est de favoriser la synergie entre nos diverses marques, en stimulant l'innovation et la croissance durable. Nous nous engageons à l'excellence et à l'expansion de notre empreinte mondiale tout en offrant une valeur exceptionnelle à nos clients et partenaires du monde entier.", contactTitle: "Contactez-nous", contactSubtitle: "N'hésitez pas à nous contacter pour des projets et des collaborations.", contactButton: "Contactez-nous",
    menu_home: "Accueil", menu_about: "À propos", menu_team: "Direction", menu_brands: "Nos Marques", menu_career: "Carrières", menu_contact: "Contact", menu_kd: "K&D History Services", menu_pep: "PeP", menu_yunan: "Yunandan Gelsin", menu_kampus: "Kampüs Giyim", menu_rezi: "ReziKyros", menu_kosmos: "Kosmos Vize",
    brand_desc_kd: "En tant que partenaire officiel de l'OTAN, elle fournit des services de conseil historique et d'analyse géopolitique dans 12 pays.", brand_desc_pep: "Une institution de monnaie électronique supervisée par la CBRT, offrant des solutions de transfert d'argent international et de portefeuille numérique.", brand_desc_yunan: "Présente des produits authentiques et traditionnels de la Grèce aux consommateurs par le biais de ses magasins en Turquie et de sa plateforme de commerce électronique.", brand_desc_kampus: "Produit des vêtements et des articles promotionnels personnalisables et axés sur le design pour les écoles, les équipes sportives et les entreprises.", brand_desc_rezi: "Développe des projets de construction résidentielle et commerciale de luxe de haute qualité en Turquie et en Europe, en mettant l'accent sur la confiance et la qualité.", brand_desc_kosmos: "En tant que seul centre de demande de visa officiel autorisé par le consulat de Grèce en Turquie, elle offre des services de visa Schengen et nationaux.",
    about_page_title: "À propos de KyroServices Global", about_section1_title: "Notre Histoire & Vision", about_section1_p1: "KyroServices Global a été fondée à Athènes en 2012 avec la vision de notre fondateur, Kyros I. Dugan, non seulement d'être un groupe d'entreprises opérant dans différents secteurs, mais aussi de construire un pont économique et culturel entre l'Europe et la Turquie. Alliant l'inspiration des profondeurs de l'histoire aux technologies du futur, notre entreprise vise à redéfinir les normes dans chaque secteur où elle est entrée depuis sa création.", about_section1_p2: "Notre parcours, qui a débuté dans des domaines de niche tels que le conseil historique et les services de visa, s'est rapidement étendu à un large éventail de domaines, notamment le textile, l'alimentation, la construction et les technologies financières, devenant ainsi une force internationale.", about_section2_title: "Notre Mission & Nos Valeurs", about_section2_p1: "Notre mission est de créer un modèle de croissance durable et innovant en créant des synergies entre toutes les sociétés de notre groupe, tout en veillant à ce que chacune de nos marques soit un leader dans son propre domaine. Nous plaçons la satisfaction du client et la qualité avant tout.", value1: "<strong>Qualité :</strong> Nous visons les normes les plus élevées dans chaque produit et service que nous offrons.", value2: "<strong>Confiance :</strong> Nous bâtissons nos relations avec toutes nos parties prenantes sur la transparence et l'honnêteté.", value3: "<strong>Innovation :</strong> Nous défions le statu quo et développons des solutions innovantes qui façonnent nos industries.", value4: "<strong>Perspective Globale :</strong> Nous pensons et agissons à l'échelle mondiale tout en respectant les valeurs locales.",
    team_page_title: "Notre Conseil d'Administration", team_kyros_bio: "Le fondateur visionnaire de KyroServices Global, dirigeant le groupe avec une perspective unique qui allie la profondeur historique à des stratégies tournées vers l'avenir.", team_alissa_bio: "Gère les opérations mondiales globales et la direction stratégique du groupe, assurant la synergie et la croissance de toutes les marques.", team_gamze_bio: "Dirige les opérations sur le marché turc dynamique et dirige également la marque « Yunandan Gelsin », jetant un pont entre deux cultures.", team_dimitri_bio: "Dirige les services de conseil historique à travers l'Europe et les États-Unis, fournissant des informations essentielles aux gouvernements et aux organisations.", team_beyza_bio: "Dirige les opérations turques de K&D History Services, adaptant l'expertise mondiale au contexte historique local.", team_sadio_bio: "Dirige la marque innovante de technologie financière PeP, stimulant son expansion dans le paysage des paiements numériques.", team_fatma_bio: "Gère Kosmos Vize, le seul centre de demande de visa officiel pour la Grèce en Turquie, garantissant un service sans faille.", team_fevzi_bio: "Dirige la marque Kampüs Giyim, en se concentrant sur la fourniture de vêtements personnalisés pour les clients éducatifs et corporatifs.", team_tugce_bio: "Dirige la marque de construction ReziKyros, en se concentrant sur le développement de projets immobiliers fiables et de haute qualité.", team_hande_bio: "Coordonne le fonctionnement réussi des franchises Burger King et Starbucks, en maintenant des normes élevées de qualité et de service.",
    career_page_title: "Carrière chez KyroServices Global", career_section1_title: "Rejoignez notre famille", career_section1_p1: "Chez KyroServices Global, nous croyons que notre plus grand atout est notre personnel. Nous favorisons un environnement de travail solidaire, collaboratif et dynamique où chaque membre de l'équipe est valorisé et a la possibilité de s'épanouir. Nous sommes une famille qui bâtit le succès ensemble, célébrant les réalisations individuelles et collectives.", career_section2_title: "Ce que nous offrons", career_section2_p1: "Nous offrons à nos employés une rémunération compétitive, des avantages sociaux complets et des opportunités continues de développement professionnel. Nous investissons dans la croissance de notre équipe car nous savons que le succès de notre entreprise repose sur l'expertise et la passion de nos employés.", career_section3_title: "Candidature Spontanée", career_section3_p1: "Nous sommes toujours à la recherche de personnes talentueuses et passionnées pour rejoindre notre équipe. Si vous pensez avoir ce qu'il faut pour contribuer à notre succès, veuillez envoyer votre CV à notre département des Ressources Humaines.",
    contact_page_title: "Contactez-nous", contact_greece_title: "Siège Mondial (Athènes)", contact_turkey_title: "Siège Turquie (Istanbul)", contact_form_title: "Envoyez-nous un message",
    kd_presence_title: "Présence Mondiale", kd_presence_text: "Opérant avec <strong>73 bureaux dans 12 pays</strong>, notre portée témoigne de notre expertise et de nos partenariats de confiance.", kd_partner_title: "Partenaire de l'OTAN", kd_partner_text: "Nous sommes fiers d'être un <strong>Partenaire Officiel de l'OTAN</strong>, fournissant des conseils historiques et géopolitiques essentiels.",
    kd_expertise_title: "Notre Expertise", kd_service1_title: "Conseil Historique", kd_service1_desc: "Fournir des perspectives stratégiques aux gouvernements et aux entreprises sur la base de données historiques et d'analyses de tendances.", kd_service2_title: "Analyse Géopolitique", kd_service2_desc: "Offrir une analyse des risques et des prévisions approfondies pour les opérations et les investissements internationaux.", kd_service3_title: "Gestion des Archives", kd_service3_desc: "Numérisation et gestion des archives historiques gouvernementales et d'entreprise.",
    form_title: "Demander un Rendez-vous", form_name: "Prénom", form_surname: "Nom", form_email: "Adresse e-mail", form_phone: "Numéro de téléphone (Optionnel)", form_country: "Pays d'Opération", form_city: "Ville", form_submit: "Envoyer la Demande", form_message: "Votre message",
    pep_page_title: "PeP - Liberté Financière Numérique", pep_intro: "PeP (Palladium Electronic Money), une marque de KyroServices Global, est un établissement de monnaie électronique fiable agréé par la BRSA et supervisé par la Banque Centrale de la République de Turquie. Elle offre des solutions pour le monde financier moderne.", pep_features_title: "Caractéristiques Clés & Avantages", pep_feature1: "<strong>Support multi-devises :</strong> Gérez des comptes en TRY, EUR, GBP, USD et plus depuis une seule application.", pep_feature2: "<strong>Transferts internationaux à bas prix :</strong> Envoyez et recevez facilement de l'argent à l'international avec des frais minimes.", pep_feature3: "<strong>Cartes PeP Visa :</strong> Cartes virtuelles sécurisées pour les achats en ligne et cartes physiques valables dans les distributeurs automatiques et les terminaux de paiement du monde entier.", pep_feature4: "<strong>Investissement en métaux précieux :</strong> Ouvrez facilement des comptes en Or, Argent et Platine via l'application.", pep_contact_button: "Contacter le Support",
    yunan_page_title: "Yunandan Gelsin - Saveurs de la mer Égée", yunan_intro: "Une marque de KyroServices Global, Yunandan Gelsin apporte les saveurs les plus authentiques et traditionnelles de la Grèce en Turquie. Nous sélectionnons soigneusement chaque produit pour offrir une véritable expérience égéenne.", yunan_stores_title: "Nos Magasins", yunan_online_title: "Acheter en Ligne", yunan_online_text: "Pour accéder à tous nos produits et faire vos achats depuis n'importe où en Turquie, visitez notre plateforme de commerce électronique.", yunan_online_button: "Visiter la Boutique en Ligne",
    kampus_page_title: "Kampüs Giyim - Nous habillons votre identité", kampus_intro: "Kampüs Giyim, une société de KyroServices Global, est un fournisseur leader de vêtements personnalisés et de produits promotionnels pour les universités, les écoles, les équipes sportives et les entreprises. Avec notre DesignLab de pointe et notre engagement envers la qualité, nous donnons vie à votre identité.", kampus_clients_title: "Qui nous servons", kampus_client1: "Établissements d'enseignement (Universités, Lycées)", kampus_client2: "Clubs et équipes sportives", kampus_client3: "Entreprises et ONG", kampus_client4: "Événements et groupes privés", kampus_products_title: "Notre Gamme de Produits", kampus_product_list: "T-shirts, sweat-shirts, sweats à capuche, casquettes, sacs en toile, tasses et une large gamme de produits de papeterie.", kampus_form_title: "Demander un devis pour une commande en gros",
    rezi_page_title: "ReziKyros - Construire en Confiance", rezi_intro: "En tant que marque de construction et de développement immobilier de KyroServices Global, ReziKyros opère en Turquie et en Europe avec une philosophie fondamentale : construire des structures fiables, de haute qualité et solides. Nous ne construisons pas seulement des bâtiments ; nous construisons une confiance durable.", rezi_philosophy_title: "Notre Philosophie", rezi_philosophy_text: "Notre fondation repose sur trois piliers : l'excellence architecturale, une qualité inébranlable des matériaux et de l'artisanat, et la création d'une valeur durable pour nos investisseurs et nos résidents.", rezi_activity_title: "Nos Domaines d'Activité", rezi_activity1: "Projets Résidentiels de Luxe", rezi_activity2: "Solutions Immobilières Commerciales", rezi_activity3: "Projets de Rénovation Urbaine", rezi_form_title: "Discutons de votre projet",
    kosmos_page_title: "Kosmos Vize - Votre Porte d'Entrée vers la Grèce", kosmos_intro: "En tant que société de KyroServices Global, Kosmos Vize est le seul centre de demande de visa officiellement autorisé par le consulat de Grèce en Turquie. Nous fournissons des services de visa fiables et efficaces depuis 2012.", kosmos_legal_title: "Statut Légal & Assurance", kosmos_legal_text: "Kosmos Vize est officiellement autorisé par l'ambassade de Grèce à Ankara et le consulat général à Istanbul. Nous n'acceptons que les demandes de visa pour la Grèce. L'évaluation et la décision finale sur les demandes sont prises exclusivement par les autorités consulaires grecques.", kosmos_services_title: "Nos Services", kosmos_service1: "Demandes de visa Schengen (jusqu'à 90 jours)", kosmos_service2: "Demandes de visa national (plus de 90 jours)", kosmos_service3: "Système de prise de rendez-vous", kosmos_service4: "Suivi de la demande", kosmos_offices_title: "Nos Bureaux",
    thank_you_title: "Merci !", thank_you_text: "Votre demande a été reçue avec succès. Nous vous contacterons dès que possible.", back_home: "Retour à l'accueil",
    page_not_found: "Page non trouvée", page_not_found_text: "La page que vous recherchez a peut-être été supprimée ou est temporairement indisponible.",
    privacy_policy: "Politique de Confidentialité"
}
